---
version: "3.7"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    env_file:
      - 'env.mysql'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/db:/data/db:rw
      - ./mysql_init.sql:/docker-entrypoint-initdb.d/mysql_init.sql:ro
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
