# Generated by Django 4.0.1 on 2022-01-07 20:24

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, verbose_name='Entry text')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date when entry was created', verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'managed': False,
            },
        ),
    ]
