networks:
  elk:
    driver: bridge
    name: elk_stack

services:
  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: 09_elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
    networks:
      elk:
        aliases:
          - 09_elasticsearch.local

  kibana:
    image: kibana:7.14.2
    container_name: kibana
    restart: always
    ports:
      - 5602:5601
    environment:
      ELASTICSEARCH_HOSTS: http://09_elasticsearch.local:9200
    networks:
      elk:
        aliases:
          - kibana.local
    depends_on:
      - elasticsearch