version: '3.3'

volumes:
  fbdata: {}

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    ports:
      - "9200:9200"
    environment:
      - node.name=es01
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
  graylog:
    image: graylog/graylog:4.2.6
    volumes:
      - ./data/graylog/graylog_journal:/usr/share/graylog/data/journal
    ports:
      - 9000:9000
      - 1514:1514
      - 1514:1514/udp
      - 12201:12201
      - 12201:12201/udp
    environment:
      - GRAYLOG_PASSWORD_SECRET=nFej4W4ufGCE4yUc
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://graylog:9000/
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/logs:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    entrypoint: ""
    command: bash -c "chown -R mysql:mysql /var/log/mysql && exec /entrypoint.sh mysqld"
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.0
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./data/mysql/logs:/var/log/mysql
      - ./data/filebeat/data:/usr/share/filebeat/data
    hostname: filebeat
    user: root
    command: filebeat -strict.perms=false