---
version: "3.7"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - /tmp/07_nginx_cache:/data/nginx/cache:rw
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    network_mode: "host"

  fastapi-web-app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: fastapi-web-app
    restart: unless-stopped
    command: bash -c "uvicorn main:app --reload"
    volumes:
      - ./app/:/app:ro
    network_mode: "host"